name: clippy

on:
  push:
    paths:
      - '.github/workflows/clippy.yml'
      - 'src/*'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: |
          C:/Program Files/LLVM
          ./llvm
        key: llvm-14.0
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "14.0"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
    - name: add cargo clippy
      run: rustup component add clippy
    - name: test
      run: cargo clippy
